export const mockPreviousTasks = [
  {
    id: "T-001",
    title: "Security Audit",
    description: "Performed full audit of all entry points.",
    deadline: "2025-05-10T18:00:00Z",
    status: "complete",
    active: false,
  },
  {
    id: "T-002",
    title: "Camera Installation",
    description: "Installed cameras on floor 3.",
    deadline: "2025-05-11T12:00:00Z",
    status: "delayed",
    active: false,
  },
  {
    id: "T-003",
    title: "System Check",
    description: "Verified alarm systems.",
    deadline: "2025-05-12T10:30:00Z",
    status: "complete",
    active: false,
  },
  {
    id: "T-004",
    title: "Gate Maintenance",
    description: "Fixed entry gate at back.",
    deadline: "2025-05-13T09:00:00Z",
    status: "delayed",
    active: false,
  },
  {
    id: "T-005",
    title: "Guard Briefing",
    description: "Conducted daily briefing for guards.",
    deadline: "2025-05-08T07:00:00Z",
    status: "complete",
    active: false,
  },
  {
    id: "T-006",
    title: "Visitor Log Review",
    description: "Checked logs for anomalies.",
    deadline: "2025-05-09T17:00:00Z",
    status: "delayed",
    active: false,
  },
];
