export const mockCurrentTasks = [
  {
    id: "T-001",
    title: "Security Audit",
    description: "Perform a full audit of all entry points.",
    deadline: "2025-05-15T18:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-002",
    title: "Camera Installation",
    description: "Install surveillance cameras on floor 3.",
    deadline: "2025-05-16T12:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-003",
    title: "System Check",
    description: "Verify all alarm systems are operational.",
    deadline: "2025-05-17T10:30:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-004",
    title: "Gate Maintenance",
    description: "Repair malfunctioning entry gate at back.",
    deadline: "2025-05-18T09:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-005",
    title: "Guard Training",
    description: "Conduct emergency response training.",
    deadline: "2025-05-20T14:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-006",
    title: "Visitor Log Review",
    description: "Review logs from past week for irregularities.",
    deadline: "2025-05-19T17:30:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-007",
    title: "Secure Server Room",
    description: "Install biometric locks in server room.",
    deadline: "2025-05-21T11:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-008",
    title: "Drone Surveillance",
    description: "Test drones for rooftop surveillance.",
    deadline: "2025-05-22T15:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-009",
    title: "Client Briefing",
    description: "Prepare materials for client security briefing.",
    deadline: "2025-05-23T08:30:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-010",
    title: "Night Patrol Schedule",
    description: "Draft new schedule for night shift patrols.",
    deadline: "2025-05-24T22:00:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-011",
    title: "Software Update",
    description: "Update access control software system.",
    deadline: "2025-05-25T13:45:00Z",
    status: "pending",
    active: true,
  },
  {
    id: "T-012",
    title: "Emergency Drill",
    description: "Conduct mock evacuation drill.",
    deadline: "2025-05-26T16:00:00Z",
    status: "pending",
    active: true,
  },
];
